import Begin from "./steps/begin";
import Login from "./steps/Login";
import Second from "./steps/second";
import Third from "./steps/third";
import Fourth from "./steps/fourth";
import Fifth from "./steps/fifth";
import Sixth from "./steps/sixth";
import Seventh from "./steps/seventh";
import Final from "./steps/final";
export { Begin, Login, Second, Third, Fourth, Fifth,Sixth,Seventh,Final };
